### ISSUE TITLE
Support for silex 2.0

### ISSUE THREAD

**Issue by EdwardIII** [romainneutron/MongoDB-ODM-Silex-Provider#15]
I've got a fork over here modified to support Silex 2.0: 

https://github.com/edwardiii/MongoDB-ODM-Silex-Provider

I can appreciate why you wouldn't want to merge this into your master, but is there an option it could exist as a separate branch perhaps?

**Comment by novia713** [comment]
yeah please

**Comment by romainneutron** [comment]
Hello, I don't maintain this project anymore, if you're interested in taking over it, drop me an email
