### ISSUE TITLE
Update composer.json

### ISSUE THREAD

**Issue by dmouse** [romainneutron/MongoDB-ODM-Silex-Provider#7]
the package doctrine/mongodb-odm has change 

https://packagist.org/packages/doctrine/mongodb-odm

require {
"doctrine/mongodb-odm": "dev-document-persister-prep"
}

**Comment by romainneutron** [comment]
The provider is compatible from version 1.0.0-beta4 and does not require latest version. It would introduces conflicts with users that need previous mongo db odm versions.

If you want to use latest version, add this requirement in your project.
